In [11]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from pathlib import Path

# Load the dataset
data_file = Path("../data/MNCAATourneyDetailedResults.csv")
df = pd.read_csv(data_file)
df.head()

,Season,DayNum,WTeamID,WScore,LTeamID,LScore,WLoc,NumOT,WFGM,WFGA,...,LFGA3,LFTM,LFTA,LOR,LDR,LAst,LTO,LStl,LBlk,LPF
0,2003,134,1421,92,1411,84,N,1,32,69,...,31,14,31,17,28,16,15,5,0,22
1,2003,136,1112,80,1436,51,N,0,31,66,...,16,7,7,8,26,12,17,10,3,15
2,2003,136,1113,84,1272,71,N,0,31,59,...,28,14,21,20,22,11,12,2,5,18
3,2003,136,1141,79,1166,73,N,0,29,53,...,17,12,17,14,17,20,21,6,6,21
4,2003,136,1143,76,1301,74,N,1,27,64,...,21,15,20,10,26,16,14,5,8,19

In [15]:
df.describe()

,Season,DayNum,WTeamID,WScore,LTeamID,LScore,NumOT,WFGM,WFGA,WFGM3,...,LFGA3,LFTM,LFTA,LOR,LDR,LAst,LTO,LStl,LBlk,LPF
count,1449.000000,1449.000000,1449.000000,1449.000000,1449.000000,1449.000000,1449.000000,1449.000000,1449.000000,1449.000000,...,1449.000000,1449.000000,1449.000000,1449.000000,1449.000000,1449.000000,1449.000000,1449.000000,1449.000000,1449.000000
mean,2013.841960,139.080745,1287.476190,75.648723,1292.518979,63.908903,0.064182,26.569358,55.981366,7.190476,...,20.931677,11.559006,16.466529,10.587992,21.289855,11.450656,11.838509,5.701173,2.928916,18.556246
std,6.639431,4.232989,103.285514,10.757312,105.991705,10.380668,0.279392,4.737391,7.227484,3.065067,...,5.858615,5.101268,6.600928,4.219547,4.472774,3.677684,3.890260,2.639951,2.016451,4.202708
min,2003.000000,134.000000,1101.000000,47.000000,1101.000000,29.000000,0.000000,13.000000,34.000000,0.000000,...,5.000000,0.000000,2.000000,1.000000,8.000000,2.000000,3.000000,0.000000,0.000000,7.000000
25%,2008.000000,136.000000,1207.000000,68.000000,1209.000000,57.000000,0.000000,23.000000,51.000000,5.000000,...,17.000000,8.000000,12.000000,8.000000,18.000000,9.000000,9.000000,4.000000,1.000000,16.000000
50%,2014.000000,137.000000,1276.000000,75.000000,1291.000000,64.000000,0.000000,26.000000,56.000000,7.000000,...,21.000000,11.000000,16.000000,10.000000,21.000000,11.000000,11.000000,6.000000,3.000000,18.000000
75%,2019.000000,139.000000,1389.000000,83.000000,1392.000000,71.000000,0.000000,30.000000,60.000000,9.000000,...,25.000000,15.000000,20.000000,13.000000,24.000000,14.000000,14.000000,7.000000,4.000000,21.000000
max,2025.000000,154.000000,1463.000000,121.000000,1471.000000,105.000000,2.000000,44.000000,84.000000,25.000000,...,42.000000,31.000000,45.000000,29.000000,42.000000,23.000000,27.000000,19.000000,13.000000,33.000000

In [12]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1449 entries, 0 to 1448
Data columns (total 34 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Season   1449 non-null   int64
 1   DayNum   1449 non-null   int64
 2   WTeamID  1449 non-null   int64
 3   WScore   1449 non-null   int64
 4   LTeamID  1449 non-null   int64
 5   LScore   1449 non-null   int64
 6   WLoc     1449 non-null   str
 7   NumOT    1449 non-null   int64
 8   WFGM     1449 non-null   int64
 9   WFGA     1449 non-null   int64
 10  WFGM3    1449 non-null   int64
 11  WFGA3    1449 non-null   int64
 12  WFTM     1449 non-null   int64
 13  WFTA     1449 non-null   int64
 14  WOR      1449 non-null   int64
 15  WDR      1449 non-null   int64
 16  WAst     1449 non-null   int64
 17  WTO      1449 non-null   int64
 18  WStl     1449 non-null   int64
 19  WBlk     1449 non-null   int64
 20  WPF      1449 non-null   int64
 21  LFGM     1449 non-null   int64
 22  LFGA     1449 non-null   int64
 23  LFGM3    1449 non-null   int64
 24  LFGA3    1449 non-null   int64
 25  LFTM     1449 non-null   int64
 26  LFTA     1449 non-null   int64
 27  LOR      1449 non-null   int64
 28  LDR      1449 non-null   int64
 29  LAst     1449 non-null   int64
 30  LTO      1449 non-null   int64
 31  LStl     1449 non-null   int64
 32  LBlk     1449 non-null   int64
 33  LPF      1449 non-null   int64
dtypes: int64(33), str(1)
memory usage: 385.0 KB

In [13]:
print(f"Length of df: {len(df)}\n")
for col in df.columns:
    print(f"{col}:")
    print(f"nunique: {df[col].nunique()}, min: {df[col].min()}, max: {df[col].max()} \n")

Length of df: 1449

Season:
nunique: 22, min: 2003, max: 2025

DayNum:
nunique: 15, min: 134, max: 154

WTeamID:
nunique: 180, min: 1101, max: 1463

WScore:
nunique: 64, min: 47, max: 121

LTeamID:
nunique: 273, min: 1101, max: 1471

LScore:
nunique: 65, min: 29, max: 105

WLoc:
nunique: 1, min: N, max: N

NumOT:
nunique: 3, min: 0, max: 2

WFGM:
nunique: 30, min: 13, max: 44

WFGA:
nunique: 46, min: 34, max: 84

WFGM3:
nunique: 20, min: 0, max: 25

WFGA3:
nunique: 39, min: 4, max: 51

WFTM:
nunique: 38, min: 0, max: 38

WFTA:
nunique: 47, min: 1, max: 48

WOR:
nunique: 26, min: 0, max: 26

WDR:
nunique: 31, min: 13, max: 43

WAst:
nunique: 27, min: 3, max: 29

WTO:
nunique: 26, min: 2, max: 28

WStl:
nunique: 18, min: 0, max: 20

WBlk:
nunique: 15, min: 0, max: 15

WPF:
nunique: 26, min: 5, max: 30

LFGM:
nunique: 26, min: 11, max: 36

LFGA:
nunique: 46, min: 37, max: 85

LFGM3:
nunique: 18, min: 0, max: 18

LFGA3:
nunique: 37, min: 5, max: 42

LFTM:
nunique: 32, min: 0, max: 31

LFTA:
nunique: 39, min: 2, max: 45

LOR:
nunique: 27, min: 1, max: 29

LDR:
nunique: 29, min: 8, max: 42

LAst:
nunique: 22, min: 2, max: 23

LTO:
nunique: 24, min: 3, max: 27

LStl:
nunique: 18, min: 0, max: 19

LBlk:
nunique: 13, min: 0, max: 13

LPF:
nunique: 27, min: 7, max: 33

In [14]:
data_length_of_single_season = len(df)/df["Season"].nunique()
data_length_of_single_season

65.86363636363636

# Data Section 1

Completed:
1. MTeams.csv & WTeans.csv
2. MNCAATourneySeed.csv & WNCAATourneySeed.csv
3. MRegularSeasonCompactResults.csv & WRegularSeasonCompactResults.csv


UP NEXT: Data Section 1 file: MNCAATourneyCompactResults.csv and WNCAATourneyCompactResults.csv

## MNCAATourneyCompactResults.csv
**Summary**: This dataset contains Season, Matchday, Winner & Looser team ID, their Scores, Match location and Num of extra time. We can find the match stage like Elite Eight, Final Four and Championship with MatchDay.

# Data Section 2: Team Box Scores

**Section Description** :
this section provides game-by-game stats at a team level(free throw attempted, defensive rebounds, turnovers) for all regular season, conference tournament, and NCAA tournament games since the 2003 season(men) and since 2010 season(women).