In [10]:
# imports
import pandas as pd
from pathlib import Path

# Load the dataset
data_file = Path("../data/MNCAATourneyDetailedResults.csv")
df = pd.read_csv(data_file)
display(f"Dataset shape: {df.shape}")
display(df.columns)
for col in df.columns:
    if df[col].isnull().sum() > 0:
        display(f"Column '{col}' has {df[col].isnull().sum()} missing values.")
display("No missing values in column")
df.head()

'Dataset shape: (1449, 34)'

Index(['Season', 'DayNum', 'WTeamID', 'WScore', 'LTeamID', 'LScore', 'WLoc',
       'NumOT', 'WFGM', 'WFGA', 'WFGM3', 'WFGA3', 'WFTM', 'WFTA', 'WOR', 'WDR',
       'WAst', 'WTO', 'WStl', 'WBlk', 'WPF', 'LFGM', 'LFGA', 'LFGM3', 'LFGA3',
       'LFTM', 'LFTA', 'LOR', 'LDR', 'LAst', 'LTO', 'LStl', 'LBlk', 'LPF'],
      dtype='str')

'No missing values in column'

,Season,DayNum,WTeamID,WScore,LTeamID,LScore,WLoc,NumOT,WFGM,WFGA,...,LFGA3,LFTM,LFTA,LOR,LDR,LAst,LTO,LStl,LBlk,LPF
0,2003,134,1421,92,1411,84,N,1,32,69,...,31,14,31,17,28,16,15,5,0,22
1,2003,136,1112,80,1436,51,N,0,31,66,...,16,7,7,8,26,12,17,10,3,15
2,2003,136,1113,84,1272,71,N,0,31,59,...,28,14,21,20,22,11,12,2,5,18
3,2003,136,1141,79,1166,73,N,0,29,53,...,17,12,17,14,17,20,21,6,6,21
4,2003,136,1143,76,1301,74,N,1,27,64,...,21,15,20,10,26,16,14,5,8,19

In [15]:
# categorizing data (nominal, ordinal, dichotomous, discrete, ratio, interval)
nominal_cols = ["Season", "DayNum", "WTeamID", "LTeamID", "WLoc", "NumOT"]
ordinal_cols = []
dichotomous_cols = []
discrete_cols = ['WFGM', 'WFGA', 'WFGM3', 'WFGA3', 'WFTM', 'WFTA', 'WOR', 'WDR', 'WAst', 'WTO', 'WStl', 'WBlk',
                 'LFGM', 'LFGA', 'LFGM3', 'LFGA3', 'LFTM', 'LFTA', 'LOR', 'LDR', 'LAst', 'LTO', 'LStl', 'LBlk']
ratio_cols = ["WScore", "LScore"]
interval_cols = []

In [19]:
if df[col].nunique() == 2:
    display(f"Column '{col}' is dichotomous with values: {df[col].unique()}")
    dichotomous_cols.append(col)
else:
    display("no dichotomous column")

'no dichotomous column'

In [22]:
# filter data from 2010 to 2022
df_filtered = df[(df['Season'] >= 2010) & (df['Season'] <= 2023)]
display(f"Filtered dataset shape: {df_filtered.shape}")
df_filtered.head()

'Filtered dataset shape: (867, 34)'

,Season,DayNum,WTeamID,WScore,LTeamID,LScore,WLoc,NumOT,WFGM,WFGA,...,LFGA3,LFTM,LFTA,LOR,LDR,LAst,LTO,LStl,LBlk,LPF
448,2010,134,1115,61,1457,44,N,0,17,44,...,21,10,18,14,20,5,7,3,5,22
449,2010,136,1124,68,1358,59,N,0,26,59,...,31,7,13,8,29,20,11,7,1,20
450,2010,136,1139,77,1431,59,N,0,23,50,...,18,7,9,6,24,15,14,8,1,24
451,2010,136,1140,99,1196,92,N,2,32,65,...,32,14,19,20,25,15,21,7,4,24
452,2010,136,1242,90,1250,74,N,0,38,69,...,19,17,21,13,20,11,13,6,4,16

In [ ]:
# test set